### PR TITLE
add/google-auth-setup

### PR DESCRIPTION
**Pull request by ajaparicio36**
### Features:
- Google auth setup through pop up
- Only accepts CPU emails
- Firebase configuration setup
- Privatized keys for Firebase

### CODE REVIEW

**Review by caspted — APPROVED** [review]
LGTM

**Review by jedmamosto — CHANGES_REQUESTED** [review]
Seems good to me but a bit of optimizations lang.

Maybe we can create an interface folder and put all interfaces (except lang siguro ka Auth) there so that other devs have a reference too on its attributes

You can update the interface User with these attributes (have the non-essential ones as optional):
- userId (id)
- userName (displayName)
- userEmail (email)
- userPhoto
- userBio
- userLikes
- userDislikes
- userTechnologies
- userType (student, faculty)
- userStatus (not enrolled, enrolled, not applicable)
- userPermissions (normal, admin)
- userBalance

Sorry medjo late na pagisipan HAHAHAH

Other than tho, nice job AJ!

**Comment by ajaparicio36** [comment]
> Seems good to me but a bit of optimizations lang.
> 
> Maybe we can create an interface folder and put all interfaces (except lang siguro ka Auth) there so that other devs have a reference too on its attributes
> 
> You can update the interface User with these attributes (have the non-essential ones as optional):
> 
> * userId (id)
> * userName (displayName)
> * userEmail (email)
> * userPhoto
> * userBio
> * userLikes
> * userDislikes
> * userTechnologies
> * userType (student, faculty)
> * userStatus (not enrolled, enrolled, not applicable)
> * userPermissions (normal, admin)
> * userBalance
> 
> Sorry medjo late na pagisipan HAHAHAH
> 
> Other than tho, nice job AJ!

Thanks for the heads up, Jed! I'll start on the changes. I just need a bit of time to get used to Firestore.

**Comment by ajaparicio36** [comment]
### Referring to @jedmamosto requested changes
I've separated User to an interfaces folder, I have also added the feature for Firestore to create User data on registration, though I would still need information on what the default data.

```export interface User {
  userId: string;
  userName: string;
  userEmail: string;
  userType: string;
  userStatus: string;
  userPermissions: string;
  userPhoto?: string;
  userBio?: string;
  userLikes?: string;
  userDislikes?: string;
  userTechnologies?: string;
  userBalance: string;
```

Here's the current default data,

```
await setDoc(userDocRef, {
          userId: user.uid,
          userName: user.displayName || "",
          userEmail: user.email || "",
          userType: "student",
          userStatus: "not enrolled",
          userPermissions: "normal",
          userBalance: "0",
});
```
        
Please message me on what the user default values should be, thank you!

**Comment by jedmamosto** [comment]
I think the default data you set is perfect HAHAHAHA like you read my mind

gj bro! i think all goods

**Review by jedmamosto — APPROVED** [review]
damn good job bro

in terms of logic all good na man

ig we'll find out once we have the frontend for it

**Pull request merged**
